# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml

stages:
  - build
  - build:docker

build:
  stage: build
  image: golang:1.20.3
  script:
    - go version
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go mod download
    - go build prometheus_webhook.go
    - ./prometheus_webhook --version
  artifacts:
    name: "${CI_JOB_NAME}"
    paths:
      - prometheus_webhook
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_SERVER_HOST == 'jihulab.com'

build:docker:alpine:
  needs:
    - job: build
      artifacts: true
  stage: build:docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t "$DOCKER_USERNAME"/prometheus-webhook:v0.0.1-alpine -f dockerfile/alpine/Dockerfile .
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push "$DOCKER_USERNAME"/prometheus-webhook:v0.0.1-alpine
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_SERVER_HOST == 'jihulab.com'
